<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'Blockspare_Page_Template_Block' ) ) {

	class Blockspare_Page_Template_Block extends Blockspare_Import_Block_Base{
		public static function get_instance() {

			static $instance = null;
			if ( null === $instance ) {
				$instance = new self();
			}
			return $instance;

		}
        public function add_block_template_library( $blocks_lists ){

            $block_library_list = array(
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Agency'],
						'key'      => 'bs_page_1',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Agency  Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/agency/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Agency'],
						'key'      => 'bs_page_2',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Agency  About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/agency/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Services','Agency'],
						'key'      => 'bs_page_3',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Agency  Services', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/agency/services/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Contact Us','Agency'],
						'key'      => 'bs_page_4',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Agency  Contact Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/agency/contact-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Lawyer'],
						'key'      => 'bs_page_5',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Lawyer Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/lawyer/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Contact Us','Lawyer'],
						'key'      => 'bs_page_6',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Lawyer Contact Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/lawyer/contact-us-2/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Restaurant'],
						'key'      => 'bs_page_7',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Restaurant Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/restaurant/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Contact Us','Restaurant'],
						'key'      => 'bs_page_8',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Restaurant Contact Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/restaurant/contact-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Restaurant'],
						'key'      => 'bs_page_9',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Restaurant About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/restaurant/about-us-2/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Menu','Restaurant'],
						'key'      => 'bs_page_10',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Restaurant Menu', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/restaurant/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Services','Restaurant'],
						'key'      => 'bs_page_11',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Restaurant Food Website', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/restaurant/food-website/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Apps'],
						'key'      => 'bs_page_12',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Apps Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/app/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Education'],
						'key'      => 'bs_page_13',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Education Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/education/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Education'],
						'key'      => 'bs_page_14',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Education About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/education/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Services','Education'],
						'key'      => 'bs_page_15',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Education Courses', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/education/serivces/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Fitness'],
						'key'      => 'bs_page_16',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Fitness Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fitness/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Pricing Table','Fitness'],
						'key'      => 'bs_page_17',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Fitness Pricing Table', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fitness/pricing-table/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Fitness'],
						'key'      => 'bs_page_18',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Fitness About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fitness/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Services','Fitness'],
						'key'      => 'bs_page_19',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Fitness Services', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fitness/services/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Testimonial','Fitness'],
						'key'      => 'bs_page_20',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Fitness Team', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fitness/team/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Real Estate'],
						'key'      => 'bs_page_21',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Real Estate Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/real-estate/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Real Estate'],
						'key'      => 'bs_page_22',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Real Estate About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/real-estate/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Property Details','Real Estate'],
						'key'      => 'bs_page_23',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Real Estate Property Details', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/real-estate/property-details/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Medical'],
						'key'      => 'bs_page_24',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Medical Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/medical/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Medical'],
						'key'      => 'bs_page_25',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Medical About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/medical/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Services','Medical'],
						'key'      => 'bs_page_26',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Medical Special Offer', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/medical/price-offer/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Frontpage','Charity'],
						'key'      => 'bs_page_27',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Charity Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/charity/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Event','Charity'],
						'key'      => 'bs_page_28',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Charity Our Event', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/charity/our-events/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Services','Charity'],
						'key'      => 'bs_page_29',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Charity Volunteer', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/charity/become-a-volunteer/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Real Charity'],
						'key'      => 'bs_page_30',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Charity About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/charity/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Home','Sport','Magazine'],
						'key'      => 'bs_page_31',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Sport Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/sport-news/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Subscription','Sport','Magazine'],
						'key'      => 'bs_page_32',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Sport Subscription', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/sport-news/subscription/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Home','Fashion','Magazine'],
						'key'      => 'bs_page_33',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Fashion Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fashion-news/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Subscription','Fashion','Magazine'],
						'key'      => 'bs_page_34',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Fashion Subscription', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fashion-news/subscription/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Home','Recipe','Magazine'],
						'key'      => 'bs_page_35',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Recipe Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/fashion-news/subscription/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Home','Pet Care'],
						'key'      => 'bs_page_36',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Pet Care Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/puppycare/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About','Pet Care'],
						'key'      => 'bs_page_37',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Pet Care About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/puppycare/about/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Contact','Pet Care'],
						'key'      => 'bs_page_38',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Pet Care Contact Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/puppycare/contact/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Home','Gadgtes'],
						'key'      => 'bs_page_39',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Gadgets Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/tech-gadgets/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['About Us','Gadgtes'],
						'key'      => 'bs_page_40',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Gadgets About Us', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/tech-gadgets/about/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    ),
					array(
						'type'     => 'page',
                        'item'     => ['Home','Construction'],
						'key'      => 'bs_page_41',
                        'imagePath'=>'pages',
						'name'     => esc_html__( 'Construction Home', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/constructions/",
						'content'  => BLOCKSPARE_PRO_PATH,	
                    )

			    );

             return array_merge_recursive( $blocks_lists, $block_library_list );
        }
    }
}
Blockspare_Page_Template_Block::get_instance()->run();