<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'Blockspare_Price_Table_Template_Block' ) ) {

	class Blockspare_Price_Table_Template_Block extends Blockspare_Import_Block_Base{
		public static function get_instance() {

			static $instance = null;
			if ( null === $instance ) {
				$instance = new self();
			}
			return $instance;

		}
        public function add_block_template_library( $blocks_lists ){

            $block_library_list = array(
					array(
						'type'     => 'block',
						'item'     => ['Price List'],
						'key'      => 'bs_price_list_1',
                        'imagePath'    => 'price-list',
						'name'     => esc_html__( 'Price List 1', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/restaurant/",
						'content'  => '<!-- wp:blockspare/blockspare-price-list {"uniqueClass":"blockspare-d15f920f-fe86-4","align":"wide","uniqueId":"d15f92"} -->
                        <div class="wp-block-blockspare-blockspare-price-list alignwide blockspare-d15f920f-fe86-4 alignwide blockspare-block-pricelist  blockspare-blocks blockspare-block-d15f92" blockspare-animation=""><div class="blockspare-pricelist-wrapper"><style>.blockspare-d15f920f-fe86-4 .blockspare-pricelist-wrapper{margin-top:30px;margin-bottom:30px;background-color:transparent}</style><!-- wp:blockspare/list-item {"uniqueClass":"blockspare-84e4f023-9432-4","priceTitle":"Baby Back Ribs","priceDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. \u003cbr\u003eUt elit tellus, luctus nec ullamcorper.","priceUnitColor":"#ffffff","backgroundColor":"#fafafa","titleFontFamily":"Roboto Condensed","titleFontWeight":"700","titleFontSubset":"latin","titleLoadGoogleFonts":true,"priceUnitFontFamily":"Roboto Condensed","priceUnitFontWeight":"700","priceUnitFontSubset":"latin","priceUnitLoadGoogleFonts":true,"descriptionFontSize":16,"descriptionFontFamily":"Roboto Condensed","descriptionFontWeight":"default","descriptionFontSubset":"latin","descriptionLoadGoogleFonts":true} -->
                        <div class="wp-block-blockspare-list-item blockspare-84e4f023-9432-4 blockspare-pircelist"><style>.blockspare-84e4f023-9432-4 .blockspare-price-list-wrap{text-align:left;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fafafa;border-radius:0px}.blockspare-84e4f023-9432-4 .blockspare-price-list-wrap .blockspare-block-icon{color:#fff;border-radius:50%}.blockspare-84e4f023-9432-4 .blockspare-price-list-wrap .blockspare-block-icon::after{background-color:#8b249c;opacity:1}.blockspare-84e4f023-9432-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-84e4f023-9432-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Roboto Condensed;font-weight:700}.blockspare-84e4f023-9432-4 .blockspare-price{color:#3c1a5b;font-size:18px!important;font-family:Roboto Condensed;font-weight:700}.blockspare-84e4f023-9432-4 .blockspare-unit{color:#ffffff;font-size:13px;font-family:Roboto Condensed;font-weight:700}.blockspare-84e4f023-9432-4 .blockspare-description{color:#6d6d6d;font-size:16px!important;font-family:Roboto Condensed;font-weight:default}@media screen and (max-width:1025px){.blockspare-84e4f023-9432-4 .blockspare-title{font-size:16px!important}.blockspare-84e4f023-9432-4 .blockspare-price,.blockspare-84e4f023-9432-4{font-size:16px!important}.blockspare-84e4f023-9432-4 .blockspare-unit{font-size:12px!important}.blockspare-84e4f023-9432-4 .blockspare-description{font-size:16px!important}}@media screen and (max-width:768px){.blockspare-84e4f023-9432-4 .blockspare-title{font-size:14px!important}.blockspare-84e4f023-9432-4 .blockspare-price{font-size:14px!important}.blockspare-84e4f023-9432-4 .blockspare-unit{font-size:10px!important}.blockspare-84e4f023-9432-4 .blockspare-description{font-size:14px!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price blockspare-hover-item"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":202,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
                        <figure class="wp-block-image aligncenter size-full is-style-rounded"><img src="https://blockspare.com/demo/default/restaurant/wp-content/uploads/sites/4/2021/09/potato.png" alt="" class="wp-image-202"/></figure>
                        <!-- /wp:image --></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title">Baby Back Ribs</h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">100</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>Ut elit tellus, luctus nec ullamcorper.</p></div></div></div>
                        <!-- /wp:blockspare/list-item -->
                        
                        <!-- wp:blockspare/list-item {"uniqueClass":"blockspare-e86d0161-d2ea-4","priceTitle":"Baby Back Ribs","priceDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. \u003cbr\u003eUt elit tellus, luctus nec ullamcorper.","priceUnitColor":"#ffffff","backgroundColor":"#fafafa","titleFontFamily":"Roboto Condensed","titleFontWeight":"700","titleFontSubset":"latin","titleLoadGoogleFonts":true,"priceUnitFontFamily":"Roboto Condensed","priceUnitFontWeight":"700","priceUnitFontSubset":"latin","priceUnitLoadGoogleFonts":true,"descriptionFontSize":16,"descriptionFontFamily":"Roboto Condensed","descriptionFontWeight":"default","descriptionFontSubset":"latin","descriptionLoadGoogleFonts":true} -->
                        <div class="wp-block-blockspare-list-item blockspare-e86d0161-d2ea-4 blockspare-pircelist"><style>.blockspare-e86d0161-d2ea-4 .blockspare-price-list-wrap{text-align:left;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fafafa;border-radius:0px}.blockspare-e86d0161-d2ea-4 .blockspare-price-list-wrap .blockspare-block-icon{color:#fff;border-radius:50%}.blockspare-e86d0161-d2ea-4 .blockspare-price-list-wrap .blockspare-block-icon::after{background-color:#8b249c;opacity:1}.blockspare-e86d0161-d2ea-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-e86d0161-d2ea-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Roboto Condensed;font-weight:700}.blockspare-e86d0161-d2ea-4 .blockspare-price{color:#3c1a5b;font-size:18px!important;font-family:Roboto Condensed;font-weight:700}.blockspare-e86d0161-d2ea-4 .blockspare-unit{color:#ffffff;font-size:13px;font-family:Roboto Condensed;font-weight:700}.blockspare-e86d0161-d2ea-4 .blockspare-description{color:#6d6d6d;font-size:16px!important;font-family:Roboto Condensed;font-weight:default}@media screen and (max-width:1025px){.blockspare-e86d0161-d2ea-4 .blockspare-title{font-size:16px!important}.blockspare-e86d0161-d2ea-4 .blockspare-price,.blockspare-e86d0161-d2ea-4{font-size:16px!important}.blockspare-e86d0161-d2ea-4 .blockspare-unit{font-size:12px!important}.blockspare-e86d0161-d2ea-4 .blockspare-description{font-size:16px!important}}@media screen and (max-width:768px){.blockspare-e86d0161-d2ea-4 .blockspare-title{font-size:14px!important}.blockspare-e86d0161-d2ea-4 .blockspare-price{font-size:14px!important}.blockspare-e86d0161-d2ea-4 .blockspare-unit{font-size:10px!important}.blockspare-e86d0161-d2ea-4 .blockspare-description{font-size:14px!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price blockspare-hover-item"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":202,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
                        <figure class="wp-block-image aligncenter size-full is-style-rounded"><img src="https://blockspare.com/demo/default/restaurant/wp-content/uploads/sites/4/2021/09/potato.png" alt="" class="wp-image-202"/></figure>
                        <!-- /wp:image --></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title">Baby Back Ribs</h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">100</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>Ut elit tellus, luctus nec ullamcorper.</p></div></div></div>
                        <!-- /wp:blockspare/list-item -->
                        
                        <!-- wp:blockspare/list-item {"uniqueClass":"blockspare-fdb0f543-0e67-4","priceTitle":"Baby Back Ribs","priceDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. \u003cbr\u003eUt elit tellus, luctus nec ullamcorper.","priceUnitColor":"#ffffff","backgroundColor":"#fafafa","titleFontFamily":"Roboto Condensed","titleFontWeight":"700","titleFontSubset":"latin","titleLoadGoogleFonts":true,"priceUnitFontFamily":"Roboto Condensed","priceUnitFontWeight":"700","priceUnitFontSubset":"latin","priceUnitLoadGoogleFonts":true,"descriptionFontSize":16,"descriptionFontFamily":"Roboto Condensed","descriptionFontWeight":"default","descriptionFontSubset":"latin","descriptionLoadGoogleFonts":true} -->
                        <div class="wp-block-blockspare-list-item blockspare-fdb0f543-0e67-4 blockspare-pircelist"><style>.blockspare-fdb0f543-0e67-4 .blockspare-price-list-wrap{text-align:left;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fafafa;border-radius:0px}.blockspare-fdb0f543-0e67-4 .blockspare-price-list-wrap .blockspare-block-icon{color:#fff;border-radius:50%}.blockspare-fdb0f543-0e67-4 .blockspare-price-list-wrap .blockspare-block-icon::after{background-color:#8b249c;opacity:1}.blockspare-fdb0f543-0e67-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-fdb0f543-0e67-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Roboto Condensed;font-weight:700}.blockspare-fdb0f543-0e67-4 .blockspare-price{color:#3c1a5b;font-size:18px!important;font-family:Roboto Condensed;font-weight:700}.blockspare-fdb0f543-0e67-4 .blockspare-unit{color:#ffffff;font-size:13px;font-family:Roboto Condensed;font-weight:700}.blockspare-fdb0f543-0e67-4 .blockspare-description{color:#6d6d6d;font-size:16px!important;font-family:Roboto Condensed;font-weight:default}@media screen and (max-width:1025px){.blockspare-fdb0f543-0e67-4 .blockspare-title{font-size:16px!important}.blockspare-fdb0f543-0e67-4 .blockspare-price,.blockspare-fdb0f543-0e67-4{font-size:16px!important}.blockspare-fdb0f543-0e67-4 .blockspare-unit{font-size:12px!important}.blockspare-fdb0f543-0e67-4 .blockspare-description{font-size:16px!important}}@media screen and (max-width:768px){.blockspare-fdb0f543-0e67-4 .blockspare-title{font-size:14px!important}.blockspare-fdb0f543-0e67-4 .blockspare-price{font-size:14px!important}.blockspare-fdb0f543-0e67-4 .blockspare-unit{font-size:10px!important}.blockspare-fdb0f543-0e67-4 .blockspare-description{font-size:14px!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price blockspare-hover-item"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":202,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
                        <figure class="wp-block-image aligncenter size-full is-style-rounded"><img src="https://blockspare.com/demo/default/restaurant/wp-content/uploads/sites/4/2021/09/potato.png" alt="" class="wp-image-202"/></figure>
                        <!-- /wp:image --></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title">Baby Back Ribs</h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">100</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>Ut elit tellus, luctus nec ullamcorper.</p></div></div></div>
                        <!-- /wp:blockspare/list-item --></div></div>
                        <!-- /wp:blockspare/blockspare-price-list -->',
                       
                    ),
                    array(
						'type'     => 'block',
						'item'     => ['Price List'],
						'key'      => 'bs_price_list_2',
                        'imagePath'    => 'price-list',
						'name'     => esc_html__( 'Price List 2', 'blockspare' ),
                        'blockLink'=>"https://blockspare.com/demo/default/restaurant/about-us/",
						'content'  => BLOCKSPARE_PRO_PATH,
                    )
				);

            return array_merge_recursive( $blocks_lists, $block_library_list );
        }
	}
}
Blockspare_Price_Table_Template_Block::get_instance()->run();